language: java
jdk:
  - oraclejdk8
sudo: required
script: mvn clean verify
after_success: mvn clean test jacoco:report coveralls:report

env:
  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to project **
    - secure: "wpdEI_KgSbUaT3JCMrOdTA"

addons:
  coverity_scan:

    # GitHub project metadata
    # ** specific to project **
    project:
      name: spdeepak/Stackoverflow
      version: 1.0.0-SNAPSHOT
      description: Stackoverflow Java API

    # Where email notification of build analysis results will be sent
    notification_email: speedpak1991@gmail.com

    # Commands to prepare for build_command
    # ** likely specific to build **
    build_command_prepend: ./configure

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    # ** likely specific to your build **
    build_command: make

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan